name: Build MinecraftWindows10Bypass

on:
 push:
   branches: [ main ]
 pull_request:
   branches: [ main ]

jobs:
 build:
   runs-on: windows-latest
   steps:
   - uses: actions/checkout@v2
   - name: Install Qt
     uses: jurplel/install-qt-action@v3
     with:
       version: 5.15.2
       modules: 'qtscript'
   - name: Build
     run: |
       qmake MinecraftWindows10Bypass.pro
       make
   - name: Upload Artifact
     uses: actions/upload-artifact@v2
     with:
       name: MinecraftWindows10Bypass
       path: release/
