name: Build MinecraftWindows10Bypass

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: Setup Microsoft Visual C++ Environment
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: 5.15.2
        modules: 'qtscript'
        
    - name: Build
      run: |
        qmake MinecraftWindows10Bypass.pro
        nmake
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: MinecraftWindows10Bypass
        path: release/